FROM python:3.6
MAINTAINER furion <_@furion.me>

# add our code
COPY . /alpha-2

# install node.js
RUN apt-get update && \
    apt-get install -y nodejs npm &&\
    rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/nodejs /usr/bin/node

# compile the dependencies
WORKDIR /alpha-2/src/static
RUN npm install

WORKDIR /alpha-2
RUN pip install -r requirements.txt

## compile sass/scss
RUN python setup.py build_sass

EXPOSE 5000
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "src.views:app"]
