FROM python:3.6-stretch
MAINTAINER furion <_@furion.me>

# add ffmpeg and ffprobe
RUN apt-get update
RUN apt-get install -y ffmpeg

# add our code
COPY . /alpha-2
WORKDIR /alpha-2
RUN pip install -r requirements.txt

# manually work around celery + redis 3 issue
RUN pip install redis==2.10.6
