FROM python:3.6-stretch
MAINTAINER furion <_@furion.me>

# add our code
COPY . /alpha-2

# install node.js
RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_8.x | bash \
    && apt-get install nodejs -yq

# compile the dependencies
WORKDIR /alpha-2/src/static
RUN npm install
RUN npm run build

WORKDIR /alpha-2
RUN pip install -r requirements.txt

## dirty hack todo
RUN pip install sqlalchemy==1.2.18

## compile sass/scss
RUN python setup.py build_sass

EXPOSE 5000
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "src.views:app"]
