FROM python:3.6.4
MAINTAINER furion <_@furion.me>

# add our code
COPY . /alpha-2
WORKDIR /alpha-2
RUN pip install -r requirements.txt

# regression fix
RUN pip install -U web3

CMD ["sh", "run-migrations.sh"]
