FROM python:3.6.4
MAINTAINER furion <_@furion.me>

# add ffmpeg and ffprobe
RUN echo "deb http://ftp.uk.debian.org/debian jessie-backports main"  | tee /etc/apt/sources.list.d/docker.list
RUN apt-get update
RUN apt-get install -y ffmpeg

# add our code
COPY . /alpha-2
WORKDIR /alpha-2
RUN pip install -r requirements.txt
RUN pip install -U web3  # regression fix
