FROM python:3.7-stretch
MAINTAINER furion <_@furion.me>

# add ffmpeg and ffprobe
RUN apt-get update
RUN apt-get install -y ffmpeg

# add our code
COPY . /alpha-2
WORKDIR /alpha-2
RUN pip install -r requirements.txt
