FROM python:3.6.4
MAINTAINER furion <_@furion.me>

# add our code
COPY . /project_root

# install node.js
RUN apt-get update && \
    apt-get install -y nodejs npm &&\
    rm -rf /var/lib/apt/lists/*
RUN ln -s /usr/bin/nodejs /usr/bin/node

# compile the dependencies
WORKDIR /project_root/src/static
RUN npm install

WORKDIR /project_root
RUN pip install -r requirements.txt

EXPOSE 5000
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "src.views:app"]
