"""add transcoder job id/pipeline

Revision ID: 0dda0b1612b5
Revises: cf80aaa17c2b
Create Date: 2017-11-09 14:47:29.713668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dda0b1612b5'
down_revision = 'cf80aaa17c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('transcoder_job_id', sa.String(length=30), nullable=True))
    op.add_column('video', sa.Column('transcoder_pipeline', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'transcoder_pipeline')
    op.drop_column('video', 'transcoder_job_id')
    # ### end Alembic commands ###
