"""add timezone,update video schema

Revision ID: 5cdd20351231
Revises: 0dda0b1612b5
Create Date: 2017-11-09 16:47:32.047057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5cdd20351231'
down_revision = '0dda0b1612b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 's3_bucket_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('video', 's3_input_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('video', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('video', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('video', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('video', 's3_input_key',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('video', 's3_bucket_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
