"""Add created_at to channel

Revision ID: 80f573200b40
Revises: 
Create Date: 2018-02-01 22:55:09.113987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f573200b40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'channel', ['id'])
    op.create_unique_constraint(None, 'video', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_constraint(None, 'channel', type_='unique')
    op.drop_column('channel', 'created_at')
    # ### end Alembic commands ###
