"""empty message

Revision ID: cf80aaa17c2b
Revises: 
Create Date: 2017-11-09 14:44:45.595276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf80aaa17c2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'channel', ['id'])
    op.create_unique_constraint(None, 'video', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='unique')
    op.drop_constraint(None, 'channel', type_='unique')
    # ### end Alembic commands ###
